import {
  GREY_LIGHTER,
  GREY_NORMAL,
  PRIMARY,
  PRIMARY_LIGHT,
  SURFACE_WHITE,
} from "@/constants";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  image: { width: "auto", height: 220, borderRadius: 16, margin: 24 },
  info: { paddingHorizontal: 24, paddingVertical: 8 },
  name: {
    fontSize: 20,
    fontFamily: "Sora_600SemiBold",
    marginBottom: 4,
    lineHeight: 30,
  },
  type: {
    fontSize: 12,
    color: GREY_LIGHTER,
    marginBottom: 8,
    lineHeight: 14.4,
  },
  infoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  iconRow: { flexDirection: "row", gap: 12, alignItems: "center" },
  iconContainer: {
    backgroundColor: "rgba(237, 237, 237, 0.35)",
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  ratingRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  ratingText: {
    fontSize: 16,
    fontFamily: "Sora_600SemiBold",
    marginLeft: 4,
    color: GREY_NORMAL,
  },
  ratingPeople: { fontSize: 12, color: GREY_LIGHTER },

  label: {
    fontSize: 16,
    fontFamily: "Sora_600SemiBold",
    marginVertical: 8,
    lineHeight: 24,
  },
  description: {
    fontSize: 14,
    fontFamily: "Sora_300Light",
    color: GREY_LIGHTER,
    lineHeight: 21,
    marginBottom: 4,
  },
  readMore: {
    fontSize: 14,
    color: PRIMARY,
    fontFamily: "Sora_600SemiBold",
    lineHeight: 21,
    marginBottom: 20,
  },
  sizeRow: { flexDirection: "row", gap: 16, marginVertical: 8 },
  sizeOption: {
    borderWidth: 1,
    borderColor: "#e3e3e3",
    backgroundColor: SURFACE_WHITE,
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
    flex: 1 / 3,
    alignItems: "center",
  },
  sizeSelected: { borderColor: PRIMARY, backgroundColor: PRIMARY_LIGHT },
  sizeText: { fontSize: 14, color: GREY_NORMAL },
  sizeTextSelected: { color: PRIMARY },
  bottomBar: {
    flexDirection: "row",
    gap: 32,
    alignItems: "center",
    paddingTop: 16,
    paddingHorizontal: 24,
    paddingBottom: 48,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    backgroundColor: SURFACE_WHITE,
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
  },
  priceLabel: { fontSize: 14, color: GREY_LIGHTER, lineHeight: 16.8 },
  price: {
    fontSize: 18,
    lineHeight: 27,
    fontFamily: "Sora_600SemiBold",
    color: PRIMARY,
  },
  buyButton: {
    flex: 1,
    backgroundColor: PRIMARY,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 16,
    alignItems: "center",
  },
  buyText: {
    color: SURFACE_WHITE,
    fontFamily: "Sora_600SemiBold",
    fontSize: 16,
  },
});
