import {
  CONTAINER,
  GREY_DARK,
  GREY_LIGHTER,
  GREY_NORMAL,
  PRIMARY,
  SURFACE_NORMAL,
  SURFACE_WHITE,
} from "@/constants";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  topSection: { backgroundImage: CONTAINER, padding: 24, paddingBottom: 80 },
  label: {
    color: GREY_LIGHTER,
    fontSize: 12,
    marginBottom: 8,
    lineHeight: 9.6,
  },
  dropdownContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    gap: 8,
    marginBottom: 24,
  },
  dropdown: {
    fontFamily: "Sora_600SemiBold",
    lineHeight: 36,
    color: SURFACE_NORMAL,
    alignSelf: "flex-start",
  },
  searchRow: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: GREY_NORMAL,
    padding: 16,
    borderRadius: 12,
  },
  filterButton: {
    marginLeft: 8,
    padding: "auto",
    backgroundColor: PRIMARY,
    borderRadius: 8,
    height: "100%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  promoCard: {
    position: "absolute",
    top: 160,
    left: 0,
    right: 0,
    marginRight: 24,
    padding: 24,
    borderRadius: 12,
    width: "100%",
    height: 180,
    zIndex: 10,
  },
  promoImage: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
  },
  promoTag: {
    position: "absolute",
    top: 32,
    left: 32,
    backgroundColor: "#bbb",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  promoText: {
    color: SURFACE_WHITE,
    fontSize: 14,
    fontFamily: "Sora_600SemiBold",
  },
  promoDescription: {
    position: "absolute",
    top: 72,
    left: 40,
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    color: SURFACE_WHITE,
    fontSize: 26,
    fontFamily: "Sora_600SemiBold",
    width: "60%",
  },
  bottomSection: { flex: 1, backgroundColor: SURFACE_WHITE, paddingTop: 90 },
  tabs: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 24,
  },
  activeTab: {
    fontSize: 14,
    fontFamily: "Sora_600SemiBold",
    color: SURFACE_WHITE,
    backgroundColor: PRIMARY,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  inactiveTab: {
    fontSize: 14,
    color: GREY_NORMAL,
    backgroundColor: "#ededed59",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  coffeeCard: {
    flex: 1 / 2,
    backgroundColor: SURFACE_WHITE,
    margin: 6,
    borderRadius: 12,
    padding: 8,
    paddingBottom: 12,
    boxShadow: "0px 2px 4px rgba(0,0,0,0.05)",
  },
  coffeeImage: {
    width: "100%",
    height: 140,
    borderRadius: 8,
    marginBottom: 8,
  },
  ratingBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    flexDirection: "row",
    gap: 8,
    padding: 8,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 24,
  },
  ratingText: {
    color: SURFACE_WHITE,
    fontSize: 8,
    fontFamily: "Sora_600SemiBold",
    lineHeight: 12,
  },
  coffeeName: {
    fontFamily: "Sora_600SemiBold",
    lineHeight: 24,
    color: GREY_DARK,
  },
  coffeeType: {
    color: GREY_LIGHTER,
    lineHeight: 14.4,
    fontSize: 12,
    marginTop: 8,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  price: {
    fontFamily: "Sora_600SemiBold",
    fontSize: 18,
    lineHeight: 27,
    color: GREY_DARK,
    marginTop: 8,
  },
});
