import {
  GREY_LIGHT,
  GREY_LIGHTER,
  GREY_NORMAL,
  PRIMARY,
  PRIMARY_LIGHT,
  SURFACE_LIGHT,
  SURFACE_WHITE,
} from "@/constants";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  toggleContainer: {
    flexDirection: "row",
    padding: 4,
    justifyContent: "center",
    marginBottom: 24,
    backgroundColor: SURFACE_WHITE,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: SURFACE_LIGHT,
  },
  toggleActive: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  toggleText: { color: GREY_NORMAL, lineHeight: 20 },
  toggleTextActive: {
    color: SURFACE_WHITE,
    fontFamily: "Sora_600SemiBold",
  },
  sectionTitle: {
    fontFamily: "Sora_600SemiBold",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 4,
  },
  address: { color: GREY_LIGHTER, marginBottom: 16 },
  pillsRow: { flexDirection: "row", gap: 10, marginTop: 8, marginBottom: 16 },
  pill: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    borderWidth: 1,
    color: GREY_NORMAL,
    backgroundColor: SURFACE_WHITE,
    borderColor: GREY_LIGHTER,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  itemRow: { flexDirection: "row", alignItems: "center", marginTop: 8 },
  coffeeImg: { width: 60, height: 60, borderRadius: 10, marginRight: 12 },
  coffeeName: {
    fontFamily: "Sora_600SemiBold",
    fontSize: 16,
    lineHeight: 24,
    color: GREY_NORMAL,
    marginBottom: 4,
  },
  coffeeType: { color: GREY_LIGHTER },
  qtyRow: { flexDirection: "row", alignItems: "center" },
  qtyText: {
    fontFamily: "Sora_600SemiBold",
    color: GREY_NORMAL,
    marginHorizontal: 18,
    fontSize: 14,
    lineHeight: 21,
  },
  dividerThick: {
    height: 4,
    backgroundColor: PRIMARY_LIGHT,
    marginVertical: 16,
    borderRadius: 2,
  },
  discountRow: {
    color: GREY_NORMAL,
    backgroundColor: SURFACE_WHITE,
    borderWidth: 1,
    borderColor: GREY_LIGHT,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 24,
  },
  discountText: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: "Sora_600SemiBold",
    flex: 1,
    marginLeft: 8,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  strike: { textDecorationLine: "line-through", color: "#999", marginRight: 4 },
  bottomBar: {
    marginTop: 30,
    paddingTop: 16,
    paddingHorizontal: 24,
    paddingBottom: 48,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    backgroundColor: SURFACE_WHITE,
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
  },
  walletRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 20,
  },
  orderBtn: {
    flex: 1,
    backgroundColor: PRIMARY,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 16,
    alignItems: "center",
  },
  orderText: {
    color: SURFACE_WHITE,
    fontFamily: "Sora_600SemiBold",
    fontSize: 16,
  },
});
